sudo: required
services: 
 - docker
 
before_install:
 - docker build -t mojogoro/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run mojogoro/react-test npm run test -- --coverage

after_success:
 - docker build -t mojogoro/multi-client ./client 
 - docker build -t mojogoro/multi-nginx ./nginx 
 - docker build -t mojogoro/multi-server ./server
 - docker build -t mojogoro/multi-worker ./worker  
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
 - docker push mojogoro/multi-client
 - docker push mojogoro/multi-nginx
 - docker push mojogoro/multi-server
 - docker push mojogoro/multi-worker
